# Generated by Django 4.1.1 on 2022-10-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_weirdstuff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeirdStuff',
        ),
    ]
