# Generated by Django 4.1.1 on 2022-11-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_comment_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
