# Generated by Django 4.1.1 on 2022-11-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_photocontest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocontest',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
